name: Deploy MkDocs
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3 ⚙️ 🐍
        uses: actions/setup-python@v2

      - name: Cache dependencies 💾
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tech/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies 🔧
        working-directory: tech
        run: make install

      - name: Build and deploy to GitHub Pages
        working-directory: tech
        run: make deploy